// GENERATED by trufi_core_utils:gen_extra_l10n — do not edit by hand.
// Edit tools/l10n/i18n/ar/*.arb and re-run: dart run trufi_core_utils:gen_extra_l10n
//
// `ar` localizations for this app (concrete classes, translations
// inlined). trufi-core ships en/es/de; this is added app-side.
// ignore_for_file: type=lint, implementation_imports

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:trufi_core_about/l10n/about_localizations.dart';
import 'package:trufi_core_home_screen/l10n/home_screen_localizations.dart';
import 'package:trufi_core_navigation/l10n/navigation_localizations.dart';
import 'package:trufi_core_poi_layers/src/l10n/poi_layers_localizations.dart';
import 'package:trufi_core_routing/l10n/routing_localizations.dart';
import 'package:trufi_core_saved_places/l10n/saved_places_localizations.dart';
import 'package:trufi_core_search_locations/l10n/search_locations_localizations.dart';
import 'package:trufi_core_settings/l10n/settings_localizations.dart';
import 'package:trufi_core_transport_list/l10n/transport_list_localizations.dart';
import 'package:trufi_core_ui/src/l10n/core_localizations.dart';

/// AboutLocalizations in `ar`.
class AboutLocalizationsAr extends AboutLocalizations {
  AboutLocalizationsAr([String locale = 'ar']) : super(locale);
  @override
  String get aboutCollapseContent => 'جمعية Trufi هي منظمة دولية غير حكومية تعمل على تسهيل الوصول إلى وسائل النقل العام. تساعد تطبيقاتنا الجميع على إيجاد أفضل طريقة للتنقل من النقطة أ إلى النقطة ب داخل مدنهم.\n\nفي العديد من المدن لا توجد خرائط أو مسارات أو تطبيقات أو جداول زمنية رسمية. لذلك نقوم بجمع المعلومات المتاحة، وأحيانًا نرسم المسارات من الصفر بالتعاون مع السكان المحليين الذين يعرفون المدينة. إن وجود نظام نقل سهل الاستخدام يسهم في تحقيق استدامة أكبر وهواء أنظف وجودة حياة أفضل.';
  @override
  String get aboutCollapseContentFoot => 'نحن بحاجة إلى راسمي خرائط ومطورين ومخططين ومختبرين والعديد من الأيادي الأخرى.';
  @override
  String get aboutCollapseTitle => 'المزيد عن جمعية Trufi';
  @override
  String get aboutContact => 'تواصل معنا';
  @override
  String get aboutLicenses => 'التراخيص';
  @override
  String get aboutOpenSource => 'تم إصدار هذا التطبيق كمصدر مفتوح على GitHub. لا تتردد في المساهمة في الكود، أو إطلاق تطبيق خاص بمدينتك.';
  @override
  String get aboutOpenSourceTitle => 'مفتوح المصدر';
  @override
  String get aboutSendFeedback => 'أرسل لنا ملاحظاتك';
  @override
  String get menuAbout => 'من نحن';
  @override
  String get trufiWebsite => 'موقع جمعية Trufi';
  @override
  String get volunteerTrufi => 'تطوّع مع Trufi';
  @override
  String aboutContent(String appName, String city) => 'هل تحتاج إلى الذهاب إلى مكان ما ولا تعرف أي حافلة أو مسار تستقل؟\nتطبيق ${appName} يجعل الأمر سهلاً!\n\nجمعية Trufi هي فريق دولي من المتطوعين. نحن نحب وسائل النقل العام، ولهذا طوّرنا هذا التطبيق لتسهيل التنقل. هدفنا هو أن نوفر لك أداة عملية تتيح لك التنقل بثقة.\n\nنحن ملتزمون بالتحسين المستمر لتطبيق ${appName} لنقدم لك معلومات أكثر دقة وفائدة باستمرار. نعلم أن نظام النقل في ${city} يشهد تغييرات لأسباب مختلفة، لذا من المحتمل ألا تكون بعض المسارات محدثة بالكامل.\n\nلكي يكون ${appName} أداة فعّالة، نعتمد على تعاون مستخدمينا. إذا كنت على علم بتغييرات في بعض المسارات أو المحطات، فإننا نشجعك على مشاركة هذه المعلومات معنا. لن تساعد مساهمتك في إبقاء التطبيق محدثًا فحسب، بل ستفيد أيضًا المستخدمين الآخرين الذين يعتمدون على ${appName}.\n\nشكرًا لاختيارك ${appName} للتنقل في ${city}، نتمنى أن تستمتع بتجربتك معنا!';
  @override
  String tagline(String city) => 'النقل العام في ${city}';
  @override
  String version(String version) => 'الإصدار ${version}';
}

class _AboutLocalizationsArDelegate extends LocalizationsDelegate<AboutLocalizations> {
  const _AboutLocalizationsArDelegate();
  @override
  bool isSupported(Locale locale) => locale.languageCode == 'ar';
  @override
  Future<AboutLocalizations> load(Locale locale) =>
      SynchronousFuture<AboutLocalizations>(AboutLocalizationsAr());
  @override
  bool shouldReload(_AboutLocalizationsArDelegate old) => false;
}

/// CoreLocalizations in `ar`.
class CoreLocalizationsAr extends CoreLocalizations {
  CoreLocalizationsAr([String locale = 'ar']) : super(locale);
  @override
  String get appName => 'تروفي';
  @override
  String get appLoading => 'جارٍ التحميل...';
  @override
  String get navHome => 'الرئيسية';
  @override
  String get navSearch => 'بحث';
  @override
  String get navFeedback => 'ملاحظات';
  @override
  String get navSettings => 'الإعدادات';
  @override
  String get navAbout => 'حول';
  @override
  String get actionSave => 'حفظ';
  @override
  String get actionCancel => 'إلغاء';
  @override
  String get actionConfirm => 'تأكيد';
  @override
  String get errorGeneric => 'حدث خطأ';
  @override
  String get errorNetwork => 'خطأ في الشبكة. يرجى التحقق من اتصالك.';
  @override
  String get errorInitialization => 'فشل في تهيئة التطبيق';
  @override
  String get actionRetry => 'إعادة المحاولة';
  @override
  String get errorPageNotFound => 'الصفحة غير موجودة';
  @override
  String get errorNoScreensRegistered => 'لا توجد شاشات مسجلة';
  @override
  String get actionGoHome => 'الذهاب إلى الرئيسية';
  @override
  String get titleError => 'خطأ';
  @override
  String get markAllAsRead => 'تعليم الكل كمقروء';
  @override
  String get initStepStarting => 'جارٍ البدء';
  @override
  String get initStepInitializing => 'جارٍ التهيئة';
  @override
  String get initStepLoadingMaps => 'جارٍ تحميل الخرائط';
  @override
  String get initStepLoadingRoutes => 'جارٍ تحميل المسارات';
  @override
  String get initStepAlmostReady => 'أوشكنا على الانتهاء';
  @override
  String get errorUnableToStart => 'تعذر بدء التشغيل';
  @override
  String get errorUnexpected => 'حدث خطأ غير متوقع';
  @override
  String get poweredByTrufi => 'مدعوم من جمعية Trufi';
  @override
  String unreadCount(int count) => '${count} غير مقروء';
}

class _CoreLocalizationsArDelegate extends LocalizationsDelegate<CoreLocalizations> {
  const _CoreLocalizationsArDelegate();
  @override
  bool isSupported(Locale locale) => locale.languageCode == 'ar';
  @override
  Future<CoreLocalizations> load(Locale locale) =>
      SynchronousFuture<CoreLocalizations>(CoreLocalizationsAr());
  @override
  bool shouldReload(_CoreLocalizationsArDelegate old) => false;
}

/// HomeScreenLocalizations in `ar`.
class HomeScreenLocalizationsAr extends HomeScreenLocalizations {
  HomeScreenLocalizationsAr([String locale = 'ar']) : super(locale);
  @override
  String get menuHome => 'الرئيسية';
  @override
  String get searchOrigin => 'اختر نقطة الانطلاق';
  @override
  String get searchDestination => 'اختر الوجهة';
  @override
  String get selectLocations => 'اختر نقطة الانطلاق والوجهة للعثور على المسارات';
  @override
  String get noRoutesFound => 'لم يتم العثور على مسارات نقل عام لهذه الرحلة. قد يعود ذلك إلى الوقت المحدد أو عدم وجود تغطية بين هاتين النقطتين. جرّب وقتًا أو وجهة مختلفة.';
  @override
  String get noRoutesFoundShort => 'لم يتم العثور على مسارات لهذه الرحلة';
  @override
  String get errorNoRoutes => 'حدث خطأ أثناء تحميل المسارات';
  @override
  String get originDestinationTooClose => 'أنت قريب جدًا من وجهتك. المشي هو الخيار الأسرع.';
  @override
  String get walk => 'مشي';
  @override
  String get yourLocation => 'موقعك الحالي';
  @override
  String get chooseOnMap => 'اختر على الخريطة';
  @override
  String get confirmLocation => 'تأكيد الموقع';
  @override
  String get selectedLocation => 'الموقع المحدد';
  @override
  String get setAsOrigin => 'تعيين كنقطة انطلاق';
  @override
  String get setAsDestination => 'تعيين كوجهة';
  @override
  String get shareRoute => 'مشاركة المسار';
  @override
  String get shareRouteOpenInApp => 'افتح في التطبيق:';
  @override
  String get tripDetails => 'تفاصيل الرحلة';
  @override
  String get departure => 'المغادرة';
  @override
  String get arrival => 'الوصول';
  @override
  String get totalDistance => 'المسافة';
  @override
  String get walking => 'المشي';
  @override
  String get tripSteps => 'خطوات الرحلة';
  @override
  String get towards => 'باتجاه';
  @override
  String get stops => 'محطات';
  @override
  String get bike => 'دراجة';
  @override
  String get train => 'قطار';
  @override
  String get transfersLabel => 'التبديلات';
  @override
  String get viewFares => 'عرض الأجور';
  @override
  String get locationPermissionTitle => 'إذن الموقع';
  @override
  String get locationPermissionDeniedMessage => 'تم رفض إذن الموقع بشكل دائم. يرجى تمكينه في إعدادات جهازك لاستخدام هذه الميزة.';
  @override
  String get locationDisabledTitle => 'خدمة الموقع معطّلة';
  @override
  String get locationDisabledMessage => 'خدمات الموقع معطّلة على جهازك. يرجى تمكينها لاستخدام هذه الميزة.';
  @override
  String get buttonCancel => 'إلغاء';
  @override
  String get buttonOpenSettings => 'فتح الإعدادات';
  @override
  String get buttonApply => 'تطبيق';
  @override
  String get searchForRoute => 'ابحث عن مسار';
  @override
  String get searchForRouteHint => 'أدخل نقطة الانطلاق والوجهة للعثور على المسارات';
  @override
  String get tooltipShare => 'مشاركة';
  @override
  String get tooltipClose => 'إغلاق';
  @override
  String get leaveNow => 'المغادرة الآن';
  @override
  String get departAt => 'المغادرة في...';
  @override
  String get arriveBy => 'الوصول قبل...';
  @override
  String get today => 'اليوم';
  @override
  String get tomorrow => 'غدًا';
  @override
  String get whenDoYouWantToTravel => 'متى تريد السفر؟';
  @override
  String get monthJan => 'يناير';
  @override
  String get monthFeb => 'فبراير';
  @override
  String get monthMar => 'مارس';
  @override
  String get monthApr => 'أبريل';
  @override
  String get monthMay => 'مايو';
  @override
  String get monthJun => 'يونيو';
  @override
  String get monthJul => 'يوليو';
  @override
  String get monthAug => 'أغسطس';
  @override
  String get monthSep => 'سبتمبر';
  @override
  String get monthOct => 'أكتوبر';
  @override
  String get monthNov => 'نوفمبر';
  @override
  String get monthDec => 'ديسمبر';
  @override
  String get buttonGo => 'انطلق';
  @override
  String get buttonDetails => 'التفاصيل';
  @override
  String get buttonTryAgain => 'حاول مرة أخرى';
  @override
  String get buttonReset => 'إعادة تعيين';
  @override
  String get routeSettings => 'إعدادات المسار';
  @override
  String get wheelchairAccessible => 'مناسب للكراسي المتحركة';
  @override
  String get wheelchairAccessibleOn => 'تتجنب المسارات الدرَج والمنحدرات الحادة';
  @override
  String get wheelchairAccessibleOff => 'تضمين جميع المسارات';
  @override
  String get walkingSpeed => 'سرعة المشي';
  @override
  String get speedSlow => 'بطيئة';
  @override
  String get speedNormal => 'عادية';
  @override
  String get speedFast => 'سريعة';
  @override
  String get maxWalkDistance => 'أقصى مسافة مشي';
  @override
  String get noLimit => 'بلا حد';
  @override
  String get transportModes => 'وسائل النقل';
  @override
  String get modeTransit => 'النقل العام';
  @override
  String get modeBicycle => 'دراجة هوائية';
  @override
  String get exitNavigation => 'إنهاء الملاحة';
  @override
  String get exitNavigationTitle => 'إنهاء الملاحة؟';
  @override
  String get exitNavigationMessage => 'هل أنت متأكد من رغبتك في التوقف عن ملاحة هذا المسار؟';
  @override
  String get buttonExit => 'خروج';
  @override
  String get arrivedMessage => 'لقد وصلت!';
  @override
  String get buttonRetry => 'إعادة المحاولة';
  @override
  String get buttonSettings => 'الإعدادات';
  @override
  String get findingRoutes => 'جارٍ البحث عن المسارات...';
  @override
  String get routingProvider => 'مزود التوجيه';
  @override
  String get autoFallback => 'التبديل التلقائي';
  @override
  String get autoFallbackDescription => 'جرّب الاتصال أولًا، واستخدم وضع عدم الاتصال إذا فشل';
  @override
  String get engineOnlineName => 'متصل';
  @override
  String get engineOnlineDescription => 'OpenTripPlanner 2.8. توجيه فوري مع إرشادات مشي مفصّلة.';
  @override
  String get engineOfflineName => 'غير متصل';
  @override
  String get engineOfflineDescription => 'توجيه قائم على GTFS. يعمل بدون إنترنت.';
  @override
  String get limitationRequiresInternet => 'يتطلب إنترنت';
  @override
  String get limitationSlower => 'استجابة أبطأ';
  @override
  String get limitationNoWalkingRoute => 'لا يوجد مسار مشي على الخريطة';
  @override
  String get estimatedTimesDisclaimer => 'أوقات السفر تقديرية وقد تختلف بسبب حركة المرور';
  @override
  String get liveVehiclesTitle => 'الحافلات المباشرة';
  @override
  String get liveVehiclesSubtitle => 'عرض الموقع المباشر للحافلات على الخريطة';
  @override
  String get liveVehiclesEnable => 'تفعيل';
  @override
  String get liveVehiclesStateOn => 'مفعّل';
  @override
  String get liveVehiclesStateOff => 'معطّل';
  @override
  String get liveVehicleTitle => 'حافلة مباشرة';
  @override
  String get liveVehicleLiveBadge => 'مباشر';
  @override
  String get placeOrigin => 'نقطة الانطلاق';
  @override
  String get placeDestination => 'الوجهة';
  @override
  String get resolvingLocation => 'جارٍ البحث عن اسم المكان…';
  @override
  String get copiedToClipboard => 'تم النسخ';
  @override
  String durationMinutes(int minutes) => '${minutes} دقيقة';
  @override
  String durationHoursMinutes(int hours, int minutes) => '${hours} س ${minutes} د';
  @override
  String distanceMeters(int meters) => '${meters} م';
  @override
  String distanceKilometers(String km) => '${km} كم';
  @override
  String transfers(int count) => '${count} تبديل';
  @override
  String departureAt(String time) => 'المغادرة في ${time}';
  @override
  String arrivalAt(String time) => 'الوصول في ${time}';
  @override
  String shareRouteTitle(String appName) => '${appName} - مسار مُشارَك';
  @override
  String shareRouteOrigin(String location) => 'نقطة الانطلاق: ${location}';
  @override
  String shareRouteDestination(String location) => 'الوجهة: ${location}';
  @override
  String shareRouteDate(String date) => 'التاريخ: ${date}';
  @override
  String shareRouteTimes(String departure, String arrival) => 'المغادرة: ${departure} ← الوصول: ${arrival}';
  @override
  String shareRouteDuration(String duration) => 'المدة: ${duration}';
  @override
  String shareRouteItinerary(String summary) => 'المسار: ${summary}';
  @override
  String operatedBy(String agency) => 'تُشغّله ${agency}';
  @override
  String co2Emissions(String grams) => '${grams} غ ثاني أكسيد الكربون';
  @override
  String departAtTime(String time) => 'المغادرة ${time}';
  @override
  String arriveByTime(String time) => 'الوصول قبل ${time}';
  @override
  String tomorrowWithTime(String time) => 'غدًا ${time}';
  @override
  String routesFound(int count) => 'تم العثور على ${count} مسار';
  @override
  String departsAt(String time) => 'يغادر ${time}';
  @override
  String liveVehicleRouteTitle(String route) => 'الخط ${route}';
  @override
  String liveVehicleSpeed(int speed) => '${speed} كم/س';
  @override
  String liveVehicleUpdatedSeconds(int seconds) => 'آخر تحديث قبل ${seconds} ث';
  @override
  String liveVehicleUpdatedMinutes(int minutes) => 'آخر تحديث قبل ${minutes} د';
  @override
  String providerNoOptions(String provider) => 'لا يحتوي مزوّد “${provider}” على خيارات قابلة للتعديل.';
}

class _HomeScreenLocalizationsArDelegate extends LocalizationsDelegate<HomeScreenLocalizations> {
  const _HomeScreenLocalizationsArDelegate();
  @override
  bool isSupported(Locale locale) => locale.languageCode == 'ar';
  @override
  Future<HomeScreenLocalizations> load(Locale locale) =>
      SynchronousFuture<HomeScreenLocalizations>(HomeScreenLocalizationsAr());
  @override
  bool shouldReload(_HomeScreenLocalizationsArDelegate old) => false;
}

/// NavigationLocalizations in `ar`.
class NavigationLocalizationsAr extends NavigationLocalizations {
  NavigationLocalizationsAr([String locale = 'ar']) : super(locale);
  @override
  String get navExitNavigation => 'إنهاء الملاحة';
  @override
  String get navExitConfirmTitle => 'إنهاء الملاحة؟';
  @override
  String get navExitConfirmMessage => 'هل أنت متأكد أنك تريد التوقف عن الملاحة على هذا المسار؟';
  @override
  String get navCancel => 'إلغاء';
  @override
  String get navExit => 'خروج';
  @override
  String get navClose => 'إغلاق';
  @override
  String get navRetry => 'إعادة المحاولة';
  @override
  String get navSettings => 'الإعدادات';
  @override
  String get navArrived => 'لقد وصلت!';
  @override
  String get navOffRoute => 'يبدو أنك خارج المسار';
  @override
  String get navWeakGps => 'إشارة GPS ضعيفة';
  @override
  String get navNext => 'التالي: ';
  @override
  String get navError => 'حدث خطأ';
  @override
  String get navStarting => 'جارٍ بدء الملاحة...';
  @override
  String get navGettingLocation => 'جارٍ تحديد موقعك';
  @override
  String get navCouldNotStartTracking => 'تعذّر بدء تتبّع الموقع';
  @override
  String get navArrivedShort => 'لقد وصلت';
  @override
  String get navOneStop => 'محطة واحدة';
  @override
  String get navFinalDestination => 'الوجهة النهائية';
  @override
  String get navPermissionDenied => 'تم رفض إذن الموقع';
  @override
  String get navPermissionPermanentlyDenied => 'تم رفض إذن الموقع بشكل دائم. يُرجى تفعيله من الإعدادات.';
  @override
  String get navLocationDisabled => 'خدمات الموقع معطّلة. يُرجى تفعيلها.';
  @override
  String get navOrigin => 'نقطة الانطلاق';
  @override
  String get navTransfer => 'نقطة التحويل';
  @override
  String get navDestination => 'الوجهة';
  @override
  String get navRoute => 'المسار';
  @override
  String navStops(int count) => '${count} محطة';
  @override
  String navExitAt(String stopName) => 'انزل عند ${stopName}';
  @override
  String navStopsRemaining(int count) => 'المحطات المتبقية: ${count}';
  @override
  String navDistanceMeters(String value) => '${value} م';
  @override
  String navDistanceKilometers(String value) => '${value} كم';
  @override
  String navDurationMinutes(int minutes) => '${minutes} د';
  @override
  String navDurationHoursMinutes(int hours, int minutes) => '${hours} س ${minutes} د';
}

class _NavigationLocalizationsArDelegate extends LocalizationsDelegate<NavigationLocalizations> {
  const _NavigationLocalizationsArDelegate();
  @override
  bool isSupported(Locale locale) => locale.languageCode == 'ar';
  @override
  Future<NavigationLocalizations> load(Locale locale) =>
      SynchronousFuture<NavigationLocalizations>(NavigationLocalizationsAr());
  @override
  bool shouldReload(_NavigationLocalizationsArDelegate old) => false;
}

/// POILayersLocalizations in `ar`.
class POILayersLocalizationsAr extends POILayersLocalizations {
  POILayersLocalizationsAr([String locale = 'ar']) : super(locale);
  @override
  String get poiLayersTitle => 'نقاط الاهتمام';
  @override
  String get goHere => 'اذهب إلى هنا';
  @override
  String get setAsOrigin => 'من هنا';
  @override
  String get pointsOfInterest => 'نقاط الاهتمام';
  @override
  String get toggleLayersOnTheMap => 'إظهار وإخفاء الطبقات على الخريطة';
  @override
  String get done => 'تم';
  @override
  String get poiCategoryTransport => 'النقل';
  @override
  String get poiCategoryFood => 'الطعام والشراب';
  @override
  String get poiCategoryShopping => 'التسوق';
  @override
  String get poiCategoryHealthcare => 'الرعاية الصحية';
  @override
  String get poiCategoryEducation => 'التعليم';
  @override
  String get poiCategoryFinance => 'المال والأعمال';
  @override
  String get poiCategoryTourism => 'السياحة';
  @override
  String get poiCategoryRecreation => 'الترفيه';
  @override
  String get poiCategoryGovernment => 'الحكومة';
  @override
  String get poiCategoryReligion => 'الدين';
  @override
  String get poiCategoryEmergency => 'الطوارئ';
  @override
  String get poiCategoryAccommodation => 'أماكن الإقامة';
  @override
  String get poiTypeBusStop => 'موقف الحافلة';
  @override
  String get poiTypePlatform => 'الرصيف';
  @override
  String get poiTypeStopPosition => 'موقف';
  @override
  String get poiTypeStation => 'محطة';
  @override
  String get poiTypeTaxiStand => 'موقف سيارات الأجرة';
  @override
  String get poiTypeParking => 'موقف سيارات';
  @override
  String get poiTypeRestaurant => 'مطعم';
  @override
  String get poiTypeCafe => 'مقهى';
  @override
  String get poiTypeFastFood => 'وجبات سريعة';
  @override
  String get poiTypeBar => 'حانة';
  @override
  String get poiTypeBakery => 'مخبز';
  @override
  String get poiTypeIceCream => 'آيس كريم';
  @override
  String get poiTypeSupermarket => 'سوبر ماركت';
  @override
  String get poiTypeConvenience => 'متجر صغير';
  @override
  String get poiTypeMarketplace => 'سوق';
  @override
  String get poiTypeClothes => 'متجر ملابس';
  @override
  String get poiTypeElectronics => 'إلكترونيات';
  @override
  String get poiTypeMall => 'مركز تسوق';
  @override
  String get poiTypeShop => 'متجر';
  @override
  String get poiTypeHospital => 'مستشفى';
  @override
  String get poiTypeClinic => 'عيادة';
  @override
  String get poiTypePharmacy => 'صيدلية';
  @override
  String get poiTypeDentist => 'طبيب أسنان';
  @override
  String get poiTypeDoctor => 'طبيب';
  @override
  String get poiTypeSchool => 'مدرسة';
  @override
  String get poiTypeUniversity => 'جامعة';
  @override
  String get poiTypeCollege => 'كلية';
  @override
  String get poiTypeKindergarten => 'روضة أطفال';
  @override
  String get poiTypeLibrary => 'مكتبة';
  @override
  String get poiTypeBank => 'بنك';
  @override
  String get poiTypeAtm => 'صراف آلي';
  @override
  String get poiTypeExchangePoint => 'صرافة عملات';
  @override
  String get poiTypeHotel => 'فندق';
  @override
  String get poiTypeAttraction => 'معلم سياحي';
  @override
  String get poiTypeViewpoint => 'نقطة مشاهدة';
  @override
  String get poiTypeMuseum => 'متحف';
  @override
  String get poiTypeMonument => 'نصب تذكاري';
  @override
  String get poiTypeArtwork => 'عمل فني';
  @override
  String get poiTypeInformation => 'معلومات';
  @override
  String get poiTypePark => 'حديقة';
  @override
  String get poiTypeSportsCentre => 'مركز رياضي';
  @override
  String get poiTypePlayground => 'ملعب أطفال';
  @override
  String get poiTypeStadium => 'ملعب رياضي';
  @override
  String get poiTypePitch => 'ملعب';
  @override
  String get poiTypeCinema => 'سينما';
  @override
  String get poiTypeTheatre => 'مسرح';
  @override
  String get poiTypeNightclub => 'ملهى ليلي';
  @override
  String get poiTypeGym => 'صالة رياضية';
  @override
  String get poiTypeSwimmingPool => 'مسبح';
  @override
  String get poiTypeTownhall => 'مبنى البلدية';
  @override
  String get poiTypeEmbassy => 'سفارة';
  @override
  String get poiTypePostOffice => 'مكتب بريد';
  @override
  String get poiTypeCourthouse => 'محكمة';
  @override
  String get poiTypePublicBuilding => 'مبنى عام';
  @override
  String get poiTypePlaceOfWorship => 'دار عبادة';
  @override
  String get poiTypeChurch => 'كنيسة';
  @override
  String get poiTypeMosque => 'مسجد';
  @override
  String get poiTypeSynagogue => 'كنيس يهودي';
  @override
  String get poiTypePolice => 'مركز شرطة';
  @override
  String get poiTypeFireStation => 'مركز إطفاء';
  @override
  String get poiTypeAmbulanceStation => 'مركز إسعاف';
  @override
  String get poiTypeHostel => 'نُزُل';
  @override
  String get poiTypeGuestHouse => 'بيت ضيافة';
  @override
  String get poiTypeMotel => 'نزل على الطريق';
  @override
  String get poiTypeApartment => 'شقة';
  @override
  String get poiTypeUnknown => 'مكان';
  @override
  String get selectPlace => 'اختر مكانًا';
  @override
  String get subcategoryTypes => 'الأنواع';
  @override
  String get selectAll => 'الكل';
  @override
  String get clearAll => 'مسح';
  @override
  String get copiedToClipboard => 'تم النسخ';
  @override
  String placesCount(int count) => '${count} مكان';
  @override
  String typesAvailable(int count) => '${count} نوع متاح';
  @override
  String typesActive(int enabled, int total) => '${enabled} من ${total} نشط';
}

class _POILayersLocalizationsArDelegate extends LocalizationsDelegate<POILayersLocalizations> {
  const _POILayersLocalizationsArDelegate();
  @override
  bool isSupported(Locale locale) => locale.languageCode == 'ar';
  @override
  Future<POILayersLocalizations> load(Locale locale) =>
      SynchronousFuture<POILayersLocalizations>(POILayersLocalizationsAr());
  @override
  bool shouldReload(_POILayersLocalizationsArDelegate old) => false;
}

/// RoutingLocalizations in `ar`.
class RoutingLocalizationsAr extends RoutingLocalizations {
  RoutingLocalizationsAr([String locale = 'ar']) : super(locale);
  @override
  String get prefsWalkingSpeed => 'سرعة المشي';
  @override
  String get prefsSpeedSlow => 'بطيئة';
  @override
  String get prefsSpeedNormal => 'عادية';
  @override
  String get prefsSpeedFast => 'سريعة';
  @override
  String get prefsMaxWalkDistance => 'أقصى مسافة للمشي';
  @override
  String get prefsNoLimit => 'بلا حد';
  @override
  String get prefsTransportModes => 'وسائل النقل';
  @override
  String get prefsModeTransit => 'النقل العام';
  @override
  String get prefsModeWalk => 'المشي';
  @override
  String get prefsModeBicycle => 'الدراجة';
  @override
  String get prefsWheelchairAccessible => 'مناسب للكراسي المتحركة';
  @override
  String get prefsWheelchairOn => 'تتجنب المسارات الدرج والمنحدرات الحادة';
  @override
  String get prefsWheelchairOff => 'تضمين جميع المسارات';
  @override
  String get serviceClosed => 'مغلق';
  @override
  String get serviceTomorrow => 'غدًا';
  @override
  String get trufiPlannerLocalDescription => 'يبحث عن المسارات باستخدام البيانات المحفوظة على جهازك.';
  @override
  String get trufiPlannerRemoteDescription => 'يبحث عن المسارات عبر خادم Trufi على الإنترنت.';
  @override
  String get trufiPlannerInfoTitle => 'حول Trufi Planner';
  @override
  String get trufiPlannerInfoIntro => 'Trufi Planner هو محرك التوجيه الخاص بنا (وليس OTP).';
  @override
  String get trufiPlannerInfoLocalBody => 'على الهاتف يعمل دون اتصال بالإنترنت بالكامل، باستخدام بيانات GTFS المضمّنة في التطبيق — وقد تختلف النتائج عن المحركات العاملة عبر الإنترنت.';
  @override
  String get trufiPlannerInfoRemoteBody => 'تستعلم نسخة الويب هذه من خادمنا؛ وقد تختلف النتائج عن OTP لأنها تستخدم خوارزمية وبيانات مختلفة.';
  @override
  String get otpOnlineDescription => 'يبحث عن المسارات عبر خدمة على الإنترنت. قد تتوفر لديه معلومات أحدث.';
  @override
  String serviceActiveClosesAt(String time) => 'نشط · يغلق في ${time}';
  @override
  String serviceClosedOpensAt(String time) => 'مغلق · يفتح في ${time}';
  @override
  String serviceClosedOpensDayAt(String day, String time) => 'مغلق · يفتح ${day} في ${time}';
  @override
  String distanceKilometers(String value) => '${value} كم';
  @override
  String distanceMeters(String value) => '${value} م';
}

class _RoutingLocalizationsArDelegate extends LocalizationsDelegate<RoutingLocalizations> {
  const _RoutingLocalizationsArDelegate();
  @override
  bool isSupported(Locale locale) => locale.languageCode == 'ar';
  @override
  Future<RoutingLocalizations> load(Locale locale) =>
      SynchronousFuture<RoutingLocalizations>(RoutingLocalizationsAr());
  @override
  bool shouldReload(_RoutingLocalizationsArDelegate old) => false;
}

/// SavedPlacesLocalizations in `ar`.
class SavedPlacesLocalizationsAr extends SavedPlacesLocalizations {
  SavedPlacesLocalizationsAr([String locale = 'ar']) : super(locale);
  @override
  String get menuSavedPlaces => 'أماكنك';
  @override
  String get yourPlaces => 'أماكنك';
  @override
  String get home => 'المنزل';
  @override
  String get work => 'العمل';
  @override
  String get favorites => 'المفضلة';
  @override
  String get customPlaces => 'المفضلة';
  @override
  String get recentPlaces => 'الأخيرة';
  @override
  String get defaultPlaces => 'الأماكن الافتراضية';
  @override
  String get setHome => 'تعيين عنوان المنزل';
  @override
  String get setWork => 'تعيين عنوان العمل';
  @override
  String get editPlace => 'تعديل المكان';
  @override
  String get removePlace => 'إزالة المكان';
  @override
  String get cancel => 'إلغاء';
  @override
  String get remove => 'إزالة';
  @override
  String get save => 'حفظ';
  @override
  String get name => 'الاسم';
  @override
  String get enterName => 'أدخل الاسم';
  @override
  String get nameRequired => 'الاسم مطلوب';
  @override
  String get selectIcon => 'اختر أيقونة';
  @override
  String get clearHistory => 'مسح';
  @override
  String get noPlacesSaved => 'لا توجد أماكن محفوظة بعد';
  @override
  String get addPlace => 'إضافة مكان';
  @override
  String get chooseOnMap => 'اختر على الخريطة';
  @override
  String get searchLocation => 'البحث عن موقع';
  @override
  String get type => 'النوع';
  @override
  String get location => 'الموقع';
  @override
  String get noLocationSelected => 'لم يتم تحديد موقع';
  @override
  String get locationRequired => 'الموقع مطلوب';
  @override
  String get locationSelected => 'تم تحديد الموقع';
  @override
  String get tapToSelectLocation => 'انقر للتحديد على الخريطة';
  @override
  String get change => 'تغيير';
  @override
  String get errorLoadingPlaces => 'خطأ في تحميل الأماكن';
  @override
  String get retry => 'إعادة المحاولة';
  @override
  String get history => 'السجل';
  @override
  String get copiedToClipboard => 'تم النسخ';
  @override
  String removePlaceConfirmation(String placeName) => 'هل أنت متأكد أنك تريد إزالة ${placeName}؟';
  @override
  String placeAlreadySaved(String placeName) => '"${placeName}" محفوظ مسبقًا في هذا الموقع';
}

class _SavedPlacesLocalizationsArDelegate extends LocalizationsDelegate<SavedPlacesLocalizations> {
  const _SavedPlacesLocalizationsArDelegate();
  @override
  bool isSupported(Locale locale) => locale.languageCode == 'ar';
  @override
  Future<SavedPlacesLocalizations> load(Locale locale) =>
      SynchronousFuture<SavedPlacesLocalizations>(SavedPlacesLocalizationsAr());
  @override
  bool shouldReload(_SavedPlacesLocalizationsArDelegate old) => false;
}

/// SearchLocationsLocalizations in `ar`.
class SearchLocationsLocalizationsAr extends SearchLocationsLocalizations {
  SearchLocationsLocalizationsAr([String locale = 'ar']) : super(locale);
  @override
  String get selectOrigin => 'اختر نقطة الانطلاق';
  @override
  String get selectDestination => 'اختر الوجهة';
  @override
  String get searchOrigin => 'ابحث عن نقطة الانطلاق...';
  @override
  String get searchDestination => 'ابحث عن الوجهة...';
  @override
  String get yourLocation => 'موقعك الحالي';
  @override
  String get chooseOnMap => 'اختر على الخريطة';
  @override
  String get yourPlaces => 'أماكنك';
  @override
  String get searchResults => 'نتائج البحث';
  @override
  String get noResultsFound => 'لا توجد نتائج';
  @override
  String get searchCornersHint => 'ابحث عن تقاطع...';
  @override
  String get copiedToClipboard => 'تم النسخ';
  @override
  String get originFieldLabel => 'من';
  @override
  String get destinationFieldLabel => 'إلى';
}

class _SearchLocationsLocalizationsArDelegate extends LocalizationsDelegate<SearchLocationsLocalizations> {
  const _SearchLocationsLocalizationsArDelegate();
  @override
  bool isSupported(Locale locale) => locale.languageCode == 'ar';
  @override
  Future<SearchLocationsLocalizations> load(Locale locale) =>
      SynchronousFuture<SearchLocationsLocalizations>(SearchLocationsLocalizationsAr());
  @override
  bool shouldReload(_SearchLocationsLocalizationsArDelegate old) => false;
}

/// SettingsLocalizations in `ar`.
class SettingsLocalizationsAr extends SettingsLocalizations {
  SettingsLocalizationsAr([String locale = 'ar']) : super(locale);
  @override
  String get onboardingTitle => 'مرحبا بك!';
  @override
  String get onboardingSubtitle => 'لنقم بإعداد تفضيلاتك';
  @override
  String get onboardingLanguageTitle => 'اختر لغتك';
  @override
  String get onboardingThemeTitle => 'اختر المظهر';
  @override
  String get onboardingThemeLight => 'فاتح';
  @override
  String get onboardingThemeDark => 'داكن';
  @override
  String get onboardingThemeSystem => 'النظام';
  @override
  String get onboardingMapTitle => 'اختر نمط الخريطة';
  @override
  String get onboardingRoutingTitle => 'اختر محرك تحديد المسارات';
  @override
  String get onboardingComplete => 'ابدأ الآن';
  @override
  String get privacyConsentTitle => 'ساعدنا في تحسين التطبيق';
  @override
  String get privacyConsentSubtitle => 'ساعدنا في تحسين التطبيق من خلال مشاركة بيانات الاستخدام المجهولة';
  @override
  String get privacyConsentInfoTitle => 'ما الذي نجمعه';
  @override
  String get privacyConsentInfoLogs => 'سجلات الأخطاء لمساعدتنا في إصلاح العلل والأعطال';
  @override
  String get privacyConsentInfoRoutes => 'عمليات البحث عن المسارات لتحسين جودة بيانات النقل العام';
  @override
  String get privacyConsentInfoAnonymous => 'جميع البيانات مجهولة تماما';
  @override
  String get privacyConsentAccept => 'موافقة ومتابعة';
  @override
  String get privacyConsentDecline => 'لا، شكرا';
  @override
  String get settingsTitle => 'الإعدادات';
  @override
  String get settingsLanguage => 'اللغة';
  @override
  String get settingsSelectLanguage => 'اختر لغتك المفضلة:';
  @override
  String get settingsTheme => 'المظهر';
  @override
  String get settingsSelectTheme => 'اختر المظهر المفضل لديك:';
  @override
  String get settingsThemeLight => 'الوضع الفاتح';
  @override
  String get settingsThemeDark => 'الوضع الداكن';
  @override
  String get settingsThemeSystem => 'افتراضي النظام';
  @override
  String get settingsMap => 'الخريطة';
  @override
  String get settingsSelectMapType => 'اختر نوع الخريطة المفضل لديك:';
  @override
  String get settingsRouting => 'البحث عن المسارات';
  @override
  String get settingsSelectRoutingEngine => 'اختر الخدمة المستخدمة لحساب مساراتك.';
  @override
  String get settingsPrivacy => 'الخصوصية';
  @override
  String get settingsPrivacySubtitle => 'ساعدنا في تحسين التطبيق';
  @override
  String get settingsPrivacyShareData => 'مشاركة بيانات الاستخدام المجهولة';
  @override
  String get settingsPrivacyShareDataDescription => 'ساعدنا في إصلاح العلل وتحسين بيانات النقل العام';
  @override
  String get engineOnlineName => 'متصل بالإنترنت';
  @override
  String get engineOnlineDescription => 'OpenTripPlanner 2.8. تحديد مسارات في الوقت الفعلي مع إرشادات مشي مفصلة.';
  @override
  String get engineOfflineName => 'غير متصل بالإنترنت';
  @override
  String get engineOfflineDescription => 'تحديد مسارات يعتمد على GTFS. يعمل بدون إنترنت.';
  @override
  String get limitationRequiresInternet => 'يتطلب اتصالا بالإنترنت';
  @override
  String get limitationSlower => 'استجابة أبطأ';
  @override
  String get limitationNoWalkingRoute => 'لا يوجد مسار مشي على الخريطة';
  @override
  String get settingsWorksOffline => 'يعمل بدون اتصال';
  @override
  String get settingsNeedsInternet => 'يتطلب اتصالًا بالإنترنت';
}

class _SettingsLocalizationsArDelegate extends LocalizationsDelegate<SettingsLocalizations> {
  const _SettingsLocalizationsArDelegate();
  @override
  bool isSupported(Locale locale) => locale.languageCode == 'ar';
  @override
  Future<SettingsLocalizations> load(Locale locale) =>
      SynchronousFuture<SettingsLocalizations>(SettingsLocalizationsAr());
  @override
  bool shouldReload(_SettingsLocalizationsArDelegate old) => false;
}

/// TransportListLocalizations in `ar`.
class TransportListLocalizationsAr extends TransportListLocalizations {
  TransportListLocalizationsAr([String locale = 'ar']) : super(locale);
  @override
  String get menuTransportList => 'الخطوط';
  @override
  String get searchRoutes => 'البحث عن الخطوط';
  @override
  String get noRoutesFound => 'لم يتم العثور على خطوط';
  @override
  String get shareRoute => 'مشاركة الخط';
  @override
  String get routeNotFound => 'الخط غير موجود';
  @override
  String get routeLoadError => 'تعذر تحميل الخط';
  @override
  String get pullDownToRefresh => 'اسحب للأسفل للتحديث';
  @override
  String get tryDifferentSearch => 'جرّب مصطلح بحث مختلف';
  @override
  String get buttonGoBack => 'رجوع';
  @override
  String get labelDistance => 'المسافة';
  @override
  String get labelStops => 'المحطات';
  @override
  String get labelMode => 'وسيلة النقل';
  @override
  String get noStopsAvailable => 'لا توجد محطات متاحة';
  @override
  String get loadingRoute => 'جارٍ تحميل الخط...';
  @override
  String get otherAgencies => 'أخرى';
  @override
  String get defaultModeBus => 'حافلة';
  @override
  String get mapSettingsTitle => 'إعدادات الخريطة';
  @override
  String get mapTypeLabel => 'نوع الخريطة';
  @override
  String get applyChanges => 'تطبيق التغييرات';
  @override
  String get stopStart => 'البداية';
  @override
  String get stopEnd => 'النهاية';
  @override
  String get stopInfoNotAvailable => 'معلومات المحطات غير متوفرة لهذا المسار';
  @override
  String get errorLoadingRoutes => 'تعذر تحميل المسارات';
  @override
  String get retry => 'إعادة المحاولة';
  @override
  String get qrShareSubtitle => 'امسح الرمز لفتح مسارات هذا المشغّل';
  @override
  String get copyQrImage => 'نسخ رمز QR';
  @override
  String get copyQrImageFailed => 'تعذر نسخ رمز QR';
  @override
  String get modeTram => 'ترام';
  @override
  String get modeSubway => 'مترو';
  @override
  String get modeRail => 'قطار';
  @override
  String get modeBus => 'حافلة';
  @override
  String get modeFerry => 'عبّارة';
  @override
  String get modeCableTram => 'ترام كابلي';
  @override
  String get modeAerialLift => 'تلفريك';
  @override
  String get modeFunicular => 'قطار جبلي مائل';
  @override
  String get modeTrolleybus => 'حافلة كهربائية';
  @override
  String get modeMonorail => 'قطار أحادي السكة';
  @override
  String get copiedToClipboard => 'تم النسخ';
  @override
  String stops(int count) => '${count} محطة';
  @override
  String routeCount(int count) => '${count} خط';
  @override
  String shareRouteMessage(String uri) => 'مشاركة: ${uri}';
  @override
  String distanceKilometers(String value) => '${value} كم';
  @override
  String distanceMeters(String value) => '${value} م';
}

class _TransportListLocalizationsArDelegate extends LocalizationsDelegate<TransportListLocalizations> {
  const _TransportListLocalizationsArDelegate();
  @override
  bool isSupported(Locale locale) => locale.languageCode == 'ar';
  @override
  Future<TransportListLocalizations> load(Locale locale) =>
      SynchronousFuture<TransportListLocalizations>(TransportListLocalizationsAr());
  @override
  bool shouldReload(_TransportListLocalizationsArDelegate old) => false;
}

/// All `ar` localization delegates for this app.
const List<LocalizationsDelegate<dynamic>> arLocalizationsDelegates = [
  const _AboutLocalizationsArDelegate(),
  const _CoreLocalizationsArDelegate(),
  const _HomeScreenLocalizationsArDelegate(),
  const _NavigationLocalizationsArDelegate(),
  const _POILayersLocalizationsArDelegate(),
  const _RoutingLocalizationsArDelegate(),
  const _SavedPlacesLocalizationsArDelegate(),
  const _SearchLocationsLocalizationsArDelegate(),
  const _SettingsLocalizationsArDelegate(),
  const _TransportListLocalizationsArDelegate(),
];
